### ISSUE TITLE
Request for Train-Test Split Information for Yuto Semantic Dataset

### ISSUE THREAD

**Issue by Serendipity-luck** [Yacovitch/EyeNet#1]
I'm currently working with the Yuto Semantic dataset, and I would like to know more about how the train-test split is performed. Specifically, could you please share the methodology or the exact division of the training and testing sets for this dataset?
For reference, here is the citation for the dataset:
Yoo, S., Ko, C., Sohn, G., & Lee, H. (2023). Yuto Semantic: a Large Scale Aerial LIDAR Dataset for Semantic Segmentation. The International Archives of the Photogrammetry, Remote Sensing and Spatial Information Sciences, 48, 209-215.

**Comment by Yacovitch** [comment]
Hi there, first of all, thank you for your interest in our work!
I set these files as my test split:
```
self.test_file_name = ["618175.81_4846250.00__618775.81_4846850.00",
                       "618775.81_4844450.00__619375.81_4845050.00",
                       "618175.81_4846850.00__618775.81_4847450.00",
                       "618175.81_4848650.00__618775.81_4849250.00",
                       "618175.81_4847450.00__618775.81_4848050.00",
                       "618775.81_4845050.00__619375.81_4845650.00",
                       "618175.81_4848050.00__618775.81_4848650.00",
                       "618775.81_4845650.00__619375.81_4846250.00",
                       "618775.81_4846250.00__619375.81_4846850.00"]
```
and the rest of them as my train split.

**Comment by Serendipity-luck** [comment]
> Hi there, first of all, thank you for your interest in our work! I set these files as my test split:
> 
> ```
> self.test_file_name = ["618175.81_4846250.00__618775.81_4846850.00",
>                        "618775.81_4844450.00__619375.81_4845050.00",
>                        "618175.81_4846850.00__618775.81_4847450.00",
>                        "618175.81_4848650.00__618775.81_4849250.00",
>                        "618175.81_4847450.00__618775.81_4848050.00",
>                        "618775.81_4845050.00__619375.81_4845650.00",
>                        "618175.81_4848050.00__618775.81_4848650.00",
>                        "618775.81_4845650.00__619375.81_4846250.00",
>                        "618775.81_4846250.00__619375.81_4846850.00"]
> ```
> 
> and the rest of them as my train split.

Thank you so much for your reply! I really appreciate the information and your help!
